services:
  openleetcode:
    image: ghcr.io/therepanic/openleetcode:latest
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - openleetcode_data:/root/.config/openleetcode
    environment:
      OPENLEETCODE_BACKEND_URL: ${OPENLEETCODE_BACKEND_URL:-http://backend:2000}

volumes:
  openleetcode_data:
