name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.2"
          cabal-version: "3.12.1.0"

      - run: |
          cabal update
          cabal build all

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.2"
          cabal-version: "3.12.1.0"

      - run: |
          cabal update
          cabal test all

  format-hs:
    name: Haskell format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.2"
          cabal-version: "3.12.1.0"

      - name: Install ormolu
        run: |
          cabal install ormolu --overwrite-policy=always
          echo "$HOME/.cabal/bin" >> "$GITHUB_PATH"

      - name: Check formatting
        run: |
          find . \
            -name '*.hs' \
            -not -path './dist-newstyle/*' \
            -exec ormolu --mode check {} +

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install --global prettier

      - run: prettier --check . --ignore-path .prettierignore

  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check --exclude runtimes"
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --exclude runtimes"
